/* Homes PK Marketing — sample data (client-side only, no backend) */

const BUSINESS = {
  name: "Homes PK Marketing",
  agent: "Kamran Abbasi",
  phones: ["0333-5492279", "0312-5492279"],
  whatsappNumbers: ["923335492279", "923125492279"],
  email: "kamranabbasi240@outlook.com",
  address: "LG 50, Gulberg Trade Centre, Business Park, Gulberg Greens, Islamabad — 440000",
  tagline: "Where Your Future Begins",
  domain: "kamranproperty.com",
  youtube: "https://www.youtube.com/@Homespk/videos",
};

function waLink(number, message) {
  return `https://wa.me/${number}?text=${encodeURIComponent(message)}`;
}

function defaultWaMessage() {
  return "Hi, I'm interested in a property listing on Homes PK Marketing";
}

function formatPKR(n) {
  if (n >= 10000000) return (n / 10000000).toFixed(2).replace(/\.00$/, "") + " Crore";
  if (n >= 100000) return (n / 100000).toFixed(2).replace(/\.00$/, "") + " Lac";
  return n.toLocaleString("en-PK");
}

const PROPERTIES = [
  {
    id: "hpk-001",
    title: "5 Marla Modern House",
    price: 32500000,
    location: "Gulberg Greens, Islamabad",
    sector: "Gulberg Greens",
    type: "House",
    purpose: "For Sale",
    status: "for-sale",
    beds: 4,
    baths: 4,
    area: "5 Marla",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A beautifully designed 5 Marla house in Gulberg Greens featuring modern architecture, premium finishes, and a bright open-plan living area. Ideal for a growing family looking for comfort and long-term value.",
    features: ["Modern kitchen", "Marble flooring", "Servant quarter", "Car porch", "Solar-ready roof", "Gas & electricity connected"],
    verified: true,
    videoUrl: "",
    featured: true,
  },
  {
    id: "hpk-002",
    title: "1 Kanal Luxury Villa",
    price: 145000000,
    location: "DHA Phase 2, Islamabad",
    sector: "DHA Islamabad",
    type: "House",
    purpose: "For Sale",
    status: "for-sale",
    beds: 6,
    baths: 7,
    area: "1 Kanal",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "An exquisite 1 Kanal villa in the heart of DHA Islamabad, offering grand living spaces, a private lawn, and top-tier construction quality. A statement home for discerning buyers.",
    features: ["Swimming pool", "Home theatre", "Imported fittings", "Landscaped lawn", "Smart home wiring", "5-car garage"],
    verified: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    featured: true,
  },
  {
    id: "hpk-003",
    title: "10 Marla Corner Plot",
    price: 21000000,
    location: "Gulberg Greens, Islamabad",
    sector: "Gulberg Greens",
    type: "Plot",
    purpose: "For Sale",
    status: "for-sale",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A prime corner plot in a fast-appreciating block of Gulberg Greens, with clear title and possession-ready status. Excellent choice for both self-construction and investment.",
    features: ["Corner location", "Possession available", "Clear title (fard)", "Wide street", "Near main boulevard"],
    verified: true,
    videoUrl: "",
    featured: true,
  },
  {
    id: "hpk-004",
    title: "2 Bed Executive Flat",
    price: 145000,
    location: "DHA Phase 5, Islamabad",
    sector: "DHA Islamabad",
    type: "Flat",
    purpose: "For Rent",
    status: "for-rent",
    beds: 2,
    baths: 2,
    area: "1100 Sqft",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A well-maintained 2 bedroom executive flat available for rent in DHA Phase 5, close to markets and parks. Ready to move in with a modern kitchen and ample natural light.",
    features: ["Lift access", "Reserved parking", "Backup generator", "Gated community", "Nearby mosque & park"],
    verified: false,
    videoUrl: "",
    featured: true,
    rentPeriod: "per month",
  },
  {
    id: "hpk-005",
    title: "4 Marla Farmhouse Plot",
    price: 18500000,
    location: "Gulberg Greens Farmhouses, Islamabad",
    sector: "Gulberg Greens",
    type: "Farmhouse",
    purpose: "For Sale",
    status: "for-sale",
    beds: 0,
    baths: 0,
    area: "4 Kanal",
    images: [
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "Escape the city on this scenic farmhouse plot in the dedicated Gulberg Greens farmhouse block — perfect for a weekend retreat or boutique farmhouse construction.",
    features: ["Farmhouse zone", "Natural surroundings", "Water access", "Boundary wall option", "Peaceful location"],
    verified: true,
    videoUrl: "",
    featured: false,
  },
  {
    id: "hpk-006",
    title: "1 Kanal House — Sold",
    price: 98000000,
    location: "Gulberg Greens, Islamabad",
    sector: "Gulberg Greens",
    type: "House",
    purpose: "For Sale",
    status: "sold",
    soldDate: "2026-06-15",
    beds: 5,
    baths: 6,
    area: "1 Kanal",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "This stunning 1 Kanal residence in Gulberg Greens was successfully sold by Kamran Abbasi — shared here as part of our track record of trusted transactions.",
    features: ["Sold by Homes PK Marketing", "Verified transaction", "Full legal handling"],
    verified: true,
    videoUrl: "",
    featured: false,
  },
  {
    id: "hpk-007",
    title: "Commercial Shop — Business Park",
    price: 27500000,
    location: "Business Park, Gulberg Greens, Islamabad",
    sector: "Gulberg Greens",
    type: "Commercial",
    purpose: "For Sale",
    status: "for-sale",
    beds: 0,
    baths: 1,
    area: "500 Sqft",
    images: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A ground-floor commercial shop in the heart of Gulberg Greens Business Park — high footfall location, ideal for retail, showroom, or office use.",
    features: ["Ground floor", "High footfall", "Wide frontage", "Elevator in building", "Ready possession"],
    verified: false,
    videoUrl: "",
    featured: false,
  },
  {
    id: "hpk-008",
    title: "5 Marla File — Gulberg Greens",
    price: 8500000,
    location: "Gulberg Greens, Islamabad",
    sector: "Gulberg Greens",
    type: "Plot",
    purpose: "For Sale",
    status: "for-sale",
    beds: 0,
    baths: 0,
    area: "5 Marla",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "An affordable 5 Marla file in a developing block of Gulberg Greens — a great entry point for first-time investors with strong future appreciation potential.",
    features: ["Balloted file", "Easy installment history", "Good location", "Investment friendly"],
    verified: false,
    videoUrl: "",
    featured: false,
  },
  {
    id: "hpk-009",
    title: "3 Bed House for Rent",
    price: 210000,
    location: "DHA Phase 3, Islamabad",
    sector: "DHA Islamabad",
    type: "House",
    purpose: "For Rent",
    status: "for-rent",
    beds: 3,
    baths: 4,
    area: "10 Marla",
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "Spacious 3 bedroom house available for rent in DHA Phase 3, featuring a large lounge, dedicated parking, and a quiet family-friendly street.",
    features: ["Dedicated parking", "Large lounge", "Family friendly street", "Recently renovated"],
    verified: true,
    videoUrl: "",
    featured: false,
    rentPeriod: "per month",
  },
  {
    id: "hpk-010",
    title: "10 Marla Plot — Sold",
    price: 19500000,
    location: "DHA Phase 2, Islamabad",
    sector: "DHA Islamabad",
    type: "Plot",
    purpose: "For Sale",
    status: "sold",
    soldDate: "2026-03-02",
    beds: 0,
    baths: 0,
    area: "10 Marla",
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A residential plot in DHA Phase 2 successfully sold through Homes PK Marketing — another satisfied client added to our growing track record.",
    features: ["Sold by Homes PK Marketing", "Verified transaction"],
    verified: true,
    videoUrl: "",
    featured: false,
  },
  {
    id: "hpk-011",
    title: "3 Bed Flat — Sold",
    price: 19500000,
    location: "DHA Phase 5, Islamabad",
    sector: "DHA Islamabad",
    type: "Flat",
    purpose: "For Sale",
    status: "sold",
    soldDate: "2026-07-20",
    beds: 3,
    baths: 3,
    area: "1800 Sqft",
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    ],
    description:
      "A well-appointed 3 bedroom flat in DHA Phase 5 sold through Homes PK Marketing — a recent addition to our track record of trusted transactions.",
    features: ["Sold by Homes PK Marketing", "Verified transaction", "Full legal handling"],
    verified: true,
    videoUrl: "",
    featured: false,
  },
];

const PROJECTS = [
  {
    id: "proj-001",
    category: "current",
    name: "Gulberg Greens Boulevard Residences",
    location: "Gulberg Greens, Islamabad",
    status: "Bookings Open",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    description: "A modern block of residential plots and homes along the main boulevard of Gulberg Greens.",
  },
  {
    id: "proj-002",
    category: "current",
    name: "DHA Valley Homes",
    location: "DHA Islamabad",
    status: "Selling Fast",
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80",
    description: "Ready and under-construction homes in a premium DHA Islamabad sector.",
  },
  {
    id: "proj-003",
    category: "collaboration",
    name: "Green Vista Enclave",
    location: "Gulberg Greens, Islamabad",
    status: "In Partnership",
    partner: "Al-Rehman Builders & Developers",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    description: "A joint development bringing gated apartment living to Gulberg Greens, in collaboration with a trusted regional builder.",
  },
  {
    id: "proj-004",
    category: "collaboration",
    name: "Capital Business Arcade",
    location: "Business Park, Gulberg Greens, Islamabad",
    status: "In Partnership",
    partner: "Capital Developers Group",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    description: "A commercial arcade project developed jointly for shops and offices in Gulberg Greens Business Park.",
  },
  {
    id: "proj-005",
    category: "construction",
    name: "Homes PK Signature Villas",
    location: "Gulberg Greens, Islamabad",
    status: "Under Construction",
    completion: "December 2026",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    description: "A limited collection of signature villas currently under construction, supervised directly by Kamran Abbasi.",
  },
  {
    id: "proj-006",
    category: "construction",
    name: "DHA Skyline Apartments",
    location: "DHA Islamabad",
    status: "Under Construction",
    completion: "June 2027",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80",
    description: "Modern apartment tower under construction, offering 2 and 3 bedroom units with skyline views.",
  },
];

const NEIGHBOURHOODS = [
  {
    name: "Gulberg Greens",
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80",
    tagline: "Islamabad's fastest-growing green community",
    count: PROPERTIES.filter((p) => p.sector === "Gulberg Greens").length,
  },
  {
    name: "DHA Islamabad",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    tagline: "Premium planned living across all phases",
    count: PROPERTIES.filter((p) => p.sector === "DHA Islamabad").length,
  },
];
